### ISSUE TITLE
Twilio international permissions

### ISSUE THREAD

**Issue by jairwin06** [Avnerus/STIR#26]
Yesterday, Caspar (in Amsterdam) received the following message when signing up as a Sleeper on an iPhone 8.

"Error: account not authorized to call {number}. Perhaps you need to enable some international permissions."

Link: twilio.com/user/account/settings/international

**Comment by Avnerus** [comment]
Yeah I checked this and it seemed to be a momentarily error in Twilio?
There are no missing permissions.
Let's see if it happens again.

**Comment by Avnerus** [comment]
Probably was a bug in Twilio
