### ISSUE TITLE
SLEEPER - error in summary screen

### ISSUE THREAD

**Issue by rlieberman** [Avnerus/STIR#29]
this happened because i set my alarm from a different device than the one where i am clicking the link. let's (if time, and pending desktop access) add some error language like "you're trying to access your summary from a different device than the one you used to create the alarm etc etc"
![bug](https://user-images.githubusercontent.com/8682329/32405530-c2673568-c13d-11e7-8110-d91eeaee0695.jpg)

**Comment by Avnerus** [comment]
Hi! So I created a STIR error page that was generally missing.
It currently looks like this:
![screenshot from 2017-11-05 16-50-03](https://user-images.githubusercontent.com/39962/32415870-74dc6964-c249-11e7-83a1-f0de18562446.png)
![screenshot from 2017-11-05 16-49-20](https://user-images.githubusercontent.com/39962/32415871-74f5402e-c249-11e7-8c8f-888c0d4b701a.png)

HTML here: https://github.com/Avnerus/STIR/blob/master/src/server/views/error.ejs
CSS here: https://github.com/Avnerus/STIR/blob/master/src/app/main.tag#L341
