### ISSUE TITLE
ROUSER - recorded a message for julia this morning but it's not showing up in admin interface

### ISSUE THREAD

**Issue by rlieberman** [Avnerus/STIR#30]
I recorded a message for Julia this morning, but she didnt get it and it is not showing up in the admin. I think that something might be going on where Sleepers are getting multiple Rousers.

For example, Avner I also left you a message just now and Julia did one earlier. Unless you were signed up for multiple alarms, this was a duplicate
![juliamessage](https://user-images.githubusercontent.com/8682329/32409388-48bf73b2-c181-11e7-8e5f-408b0e57b94b.jpg)

**Comment by Avnerus** [comment]
I cleared the database today.
Also this might have been a dummy alarm
