### ISSUE TITLE
SLEEPER - summary link wrong

### ISSUE THREAD

**Issue by jairwin06** [Avnerus/STIR#36]
After my call this morning I received the summary text with a link to the wrong screen. It went to the Sleeper welcome screen ("If you're like nearly half the other humans...")

**Comment by Avnerus** [comment]
can I see the link please?

**Comment by jairwin06** [comment]
The URL?

**Comment by Avnerus** [comment]
Yeah

**Comment by jairwin06** [comment]
https://stir.today/sleeper/alarm/59fe28a4f21efb1318921181/summary

**Comment by Avnerus** [comment]
Looks fine.
What happens when you try to click it now? (From the same device that created the alarm)

**Comment by jairwin06** [comment]
It takes me to the same screen (Sleeper welcome)

**Comment by jairwin06** [comment]
Jackson also had a problem. When he clicked his summary URL he got a 404 message.

**Comment by Avnerus** [comment]
Checking about the welcome.
Did Jackson go to the summary URL from the same device he used to set the alarm?

**Comment by Avnerus** [comment]
Tell Jackson also to try again now

**Comment by jairwin06** [comment]
Wait, sorry about the Jackson thing. It was actually bc he went on the wrong device. The summary link on the device worked for him well.

**Comment by Avnerus** [comment]
let's watch this, closing issue for now
