### ISSUE TITLE
ROUSER + SLEEPER - swap out home screen icons

### ISSUE THREAD

**Issue by rlieberman** [Avnerus/STIR#39]
art attached
![rouser-icon](https://user-images.githubusercontent.com/8682329/32419683-1fef1002-c24c-11e7-8a96-f1ac642851fb.jpg)
![sleeper-icon](https://user-images.githubusercontent.com/8682329/32419684-1ff86896-c24c-11e7-80f8-3811654049ee.jpg)

**Comment by Avnerus** [comment]
Hey so I"m gonna start with putting just one because two may cause complications.
Which one will it be?

**Comment by Avnerus** [comment]
Hey I'm not sure why but there's something strange with the rouser image. It doesn't really work. Is there something different about the format of the rouser image?

**Comment by rebeccalieb** [comment]
lets do the black background with white text for the icon

**Comment by Avnerus** [comment]
ok
