### ISSUE TITLE
SLEEPER - twitter login bug

### ISSUE THREAD

**Issue by rebeccalieb** [Avnerus/STIR#42]
from my boyfriend "i  tried logging into Twitter which continued to get me nowhere. It would "authorize app" but then take me back to the same screen where I choose between FB and Twitter."

he is using an iphone btw

**Comment by jairwin06** [comment]
This is similar to the bug I have been encountering, with both fb and
twitter. It always takes me back to that same screen.

**Comment by Avnerus** [comment]
Fixed!
