### ISSUE TITLE
SLEEPER - FB authentication through app?

### ISSUE THREAD

**Issue by rebeccalieb** [Avnerus/STIR#43]
is there a way to automatically open the FB app to authenticate if people have it on their phone? Or does it always beed to happen through the browser

if not or if it's a lot of work, no big deal

**Comment by Avnerus** [comment]
Unfortunately that is not possible when using our way of authentication, which is the best way for mobile web apps.
Is there any problem with the current flow?

**Comment by rebeccalieb** [comment]
No was just asking
Let's close the issue :)

**Comment by Avnerus** [comment]
Ok :)
