### ISSUE TITLE
SLEEPER - able to schedule alarm for less than 8 hours away

### ISSUE THREAD

**Issue by rlieberman** [Avnerus/STIR#47]
I scheduled this alarm for 2am and it went through without any error messages
<img width="516" alt="screen shot 2017-11-09 at 9 25 25 pm" src="https://user-images.githubusercontent.com/8682329/32640017-90fb945a-c594-11e7-8258-a99a763fac0a.png">

**Comment by Avnerus** [comment]
Yes this is enabled for NFB's QC.
Closing issue.
