### ISSUE TITLE
ADMIN - not sure why the  message i just left isn't showing up

### ISSUE THREAD

**Issue by rlieberman** [Avnerus/STIR#48]
I left a message for Avner and I want to see it but it's not showing up in the admin.

The admin also looks funky to me, why is delivered marked to true when recorded is marked to false?

<img width="928" alt="screen shot 2017-11-11 at 1 11 51 pm" src="https://user-images.githubusercontent.com/8682329/32692221-113b16e2-c6e2-11e7-8a53-46770fd643ae.png">

**Comment by Avnerus** [comment]
So the message that you left for Avner was a dummy one. You can spot them usually if it says you can record in all 3 languages.
That alarm you're saying was indeed delivered, as we are delivering alarms without a recording as well.
Can I close the issue?

**Comment by rlieberman** [comment]
question answered. closing the issue
