### ISSUE TITLE
SLEEPER - change volume / refine fade on backing tracks

### ISSUE THREAD

**Issue by rlieberman** [Avnerus/STIR#50]
My preview of the message seemed too loud. But the sound made such a difference, wow :)

If I have some samples to send to TK, then I can get final feedback from him

**Comment by Avnerus** [comment]
Yes, I am waiting for TK to do the mastering so that all tracks are at the same level, and then we can do the balance between that and the recording.

**Comment by rlieberman** [comment]
Ah ok cool.

**Comment by rlieberman** [comment]
closing this
