### ISSUE TITLE
ROUSER / ADMIN - noticing duplicate alarms

### ISSUE THREAD

**Issue by rlieberman** [Avnerus/STIR#51]
I'm noticing people in the admin that already have a voicemail recorded for them, and they're still showing up in my queue as a Rouser. Then when I record a message for them, it replaces what was there before.

I think that's a bug so i am filing an issue for it.

**Comment by Avnerus** [comment]
Are you sure that you went through the "submit recording" phase and go the thank you screen?

**Comment by Avnerus** [comment]
That's fine
